lls-frontend/language-coursescript

- snippets/language-coursescript.cson
> update sequece from Text to Audio

- snippets/language-coursescript.cson
> Update indent for tips

- grammars/coursescript.cson
> Add metadata grammar and fix the end of invalid string literals

- snippets/language-coursescript.cson
> add_wordguess_chooseword_wordfragments

- package.json
- snippets/language-coursescript.cson
> Change wordfragments add sc

- components/App.jsx
- lib/language-coursescript-view.js
- lib/language-coursescript.js
- package-lock.json
- package.json
- 增加对LT和PT的支持
- 源文件鼠标位置随题目变化
- 修复其他一些小Bug
> New Preview Feature

- components/App.jsx
- package-lock.json
- package.json
- styles/coursescript-preview.less
> Upgrade lib

- snippets/language-coursescript.cson
Before | After
-- | --
[TYPE MCP1]ID: Audio: Opts: Text:Text:Pic(checked=true):TR: | [TYPE MCP1]ID: Audio: Opts: Pic(checked=true):Pic: Pic: Pic:TR:
[TYPE MCP2]ID:Audio:Opts: Text:Text:Pic(checked=true):TR: | [TYPE MCP2]ID:Audio:Opts: Pic(checked=true):Pic: Pic: Pic: Pic:TR:
[TYPE MCQ1] ID: Audio: Pic: Text:Opts:    Text(checked=true):    Text:    Text:    Text: TR: | [TYPE MCQ1] ID: Audio: Pic: Opts:    Text(checked=true):    Text:    Text:    Text: TR:
[TYPE MCQ3] ID: Audio: Pic:Text:Opts:    Text(checked=true):    Text:    Text:    Text:TR: | [TYPE MCQ3] ID: Audio: Text: Opts:    Text(checked=true):    Text:    Text:    Text:TR:
Missing | [TYPE MCQ4b] ID: Audio: Text: Opts:    Text(checked=true):    Text:    Text: TR:
[TYPE MCQ5] ID: Audio: Pic(checked=true): | [TYPE …
> Summary: Re-org snippets template

- components/App.jsx
- components/Search.jsx
- components/SearchItem.jsx
- keymaps/language-coursescript.cson
- lib/language-coursescript-search.js
- lib/language-coursescript.js
- menus/language-coursescript.cson
- package-lock.json
- package.json
- styles/coursescript-preview.less
1. 添加资源搜索功能
2. 修复Dictation题型展示Bug
> Search Resource

- snippets/language-coursescript.cson
> add_wordguess_sentenceFragments

- snippets/language-coursescript.cson
> snippets: update snippets

- components/App.jsx
- components/Search.jsx
- components/SearchItem.jsx
- keymaps/language-coursescript.cson
- lib/language-coursescript-search.js
- lib/language-coursescript-view.js
- lib/language-coursescript.js
- package-lock.json
- package.json
- 添加快捷键 focus 搜索框（没有找到其他办法，无法自动 focus）
- 添加 code 复制功能
- 报错信息取消自动收起，改为必须用户手动关闭
> New Feature 3.4.0

- components/App.jsx
- components/Search.jsx
- components/SearchItem.jsx
- components/SelectType.jsx
- package-lock.json
- package.json
- styles/coursescript-preview.less
- video 搜索添加 VideoClip，支持复制 code
- 增加 BE 的 Preview 入口
- 修复了MCP 3 和 SentenceCompletion 题型显示问题
> New Feature

- components/Search.jsx
- keymaps/language-coursescript.cson
- lib/language-coursescript-search.js
- lib/language-coursescript.js
- package-lock.json
- package.json
- styles/coursescript-preview.less
> New Features

- snippets/language-coursescript.cson
> add_sp_ra_delete_tips

- components/SelectType.jsx
- package.json
- snippets/language-coursescript.cson
> feat(sprout): modify entry name

- package-lock.json
- package.json
- Darwin new course PreDialogPlay
- Darwin new course SpeakingMCQ
- fix AnswerList user selected status on change
> feat: course pre dialog play & speaking mcq

- grammars/coursescript.cson
add keywords 'Mix', 'Scene' for sprout new question, for a new question
```
[TYPE A2P_SQMA]
ID: 1
Audio(id=2): Which of the following words are related to food?
Opts:
Mix:
Pic(id=3, check=true): Dan.png
Audio(id=xxx): dan.mcp3
Text: dan
Mix:
Pic(id=4, check=true): Tina.png
Audio(id=xxx): tina.mp3
Text: tina
Mix:
Pic(id=5): dog.png
Audio(id=xxx): dog.mp3
Text: dog
Scene:
Pic(id=6): farm.png
coordinate(x=121,y=22,w=22,h=33)
coordinate(x=234,y=345,w=22,h=23)
coordinate(x=223,y=232,w=11,h=13)
```
There seems to be no other alternative
For better display …
> feat(grammar): add keywords 'Mix', 'Scene' for sprout new question

- package-lock.json
- package.json
> feat: update component-lib version to add a2tsqma part

- package-lock.json
- package.json
- snippets/language-coursescript.cson
> feat: add assessment and a2t_mqsa

- package-lock.json
- package.json
- snippets/language-coursescript.cson
> feat(snippets): add SO, P2T, DubShow, A2T2, A2P_MQSA, A2P_SQMA

- package-lock.json
- package.json
> fix: update coursescript-lib version to 2.5.6

- package-lock.json
- package.json
- snippets/language-coursescript.cson
>  feat: update snippets && coursescript-lib version

- package-lock.json
- package.json
> feat: add canvas loading

- components/SelectType.jsx
- package-lock.json
- package.json
- 更新 coursescript-lib 支持 Bell 的题型
- 添加 Bell & 旅游英语的 preview 入口
> Bell & Tourism

- grammars/coursescript.cson
- package-lock.json
- package.json
> feat: update to 2.6.10

- components/Search/Filter.jsx
- components/Search/index.jsx
> fix: search baseQuery

- grammars/coursescript.cson
- package-lock.json
- package.json
> update @lls/coursescript-lib to 2.6.11

- snippets/language-coursescript.cson
> snippets: add mcqx

- snippets/language-coursescript.cson
> add_explanation_textteaching

- package-lock.json
- package.json
> feat: change sprout canvas check

- snippets/language-coursescript.cson
> snippets: for darwin course snippets

- components/Search/Filter.jsx
- grammars/coursescript.cson
> Update Grammars & Default search type

- grammars/coursescript.cson
> hotfix: quote highlight

- package.json
- yarn.lock
> update to 2.8.7

- grammars/coursescript.cson
- keymaps/language-coursescript.cson
- lib/language-coursescript.js
- menus/language-coursescript.cson
- package.json
> Insert Bell ID

- package.json
- yarn.lock
> feat: update previewlib to 2.10.2

- package.json
- yarn.lock
> fix: episode click color

- components/SelectType.jsx
- package.json
- yarn.lock
support lingochamp preview
N/A
lingochamp team can preivew their coursescript
N/A
N/A
> feat: support lingochamp

- components/App.jsx
- package.json
- yarn.lock
> fix: lingochamp activity line id

- components/SelectType.jsx
> feat: tourism course type change

- components/SelectType.jsx
- package.json
- snippets/language-coursescript.cson
- yarn.lock
> feat: support kion

- package.json
- yarn.lock
> feat: update course lib version to 2.13.1

- components/SelectType.jsx
- package.json
- yarn.lock
> feat: support kion exam

- components/Search/index.jsx
- styles/coursescript-preview.less
> feat: copy feedback

- package.json
- yarn.lock
> fix: video slice id

- package.json
- yarn.lock
> fix: kion part id

- package.json
- yarn.lock
> fix: kion chapters id

- grammars/coursescript.cson
- package.json
- snippets/language-coursescript.cson
- yarn.lock
> update course lib version && snippets

- components/SelectType.jsx
> feat: change tourism course type

- package.json
- yarn.lock
> feat: c2e & semi sent construct

- package.json
- yarn.lock
> feat: update preview lib

- snippets/language-coursescript.cson
> add_c2t_semisentence_freetalkdescription

- package.json
- yarn.lock
> fix(sprout): fix text highlight

- package.json
- snippets/language-coursescript.cson
- yarn.lock
> update course lib version to 2.14.4 && add snippets

- snippets/language-coursescript.cson
> fix: snippets indent

- components/SelectType.jsx
- package.json
- yarn.lock
> feat: add Darwin Business & Kion new Activity

- package.json
- yarn.lock
> feat: update course lib version to 2.14.6

- components/Search/index.jsx
> feat: add is tts -1

- components/SelectType.jsx
- package.json
- yarn.lock
> feat: support telis preview

- package.json
- yarn.lock
> feat: darwin activity update

- package.json
- yarn.lock
> fix: text sequence text

- package.json
- yarn.lock
> fix: hightlight

- package.json
- yarn.lock
> fix: tr audio in content & text color

- package.json
- yarn.lock
> fix: tr audio

- components/Search/index.jsx
- package.json
- yarn.lock
> fix: telis course

- snippets/language-coursescript.cson
> Add matching mca mct mcp

- package.json
- yarn.lock
> feat: telis write paraphrase

- package.json
- snippets/language-coursescript.cson
- yarn.lock
> feat: update course lib version & snippets

- components/SelectType.jsx
- lib/language-coursescript.js
> feat: preview course setting

- package.json
- yarn.lock
> update @lls/coursescript-lib version

- snippets/language-coursescript.cson
> add_new_format

- components/SelectType.jsx
- components/course-types.js
- lib/language-coursescript.js
> feat: add darwin hifi

- package.json
- yarn.lock
> feat: update @lls/coursescript-lib version

- components/Search/AudioItem.jsx
➜  language-coursescript git:(master)
> feat: CMS-315

- components/App.jsx
- components/Search/AudioItem.jsx
- components/api-urls.js
- lib/language-coursescript-view.js
- lib/language-coursescript.js
change filenames of video and picture
> Feat/cms 314: change filenames of video and picture

- components/course-types.js
- package.json
- snippets/language-coursescript.cson
- yarn.lock
> feat: support aix course & snippets

- snippets/language-coursescript.cson
> feat(snippets): add indentation to aix course snippets

- package.json
- snippets/language-coursescript.cson
- yarn.lock
> feat: support aix 0.4 course snippets

- components/course-types.js
- package.json
- snippets/language-coursescript.cson
- yarn.lock
> feat(lingokids): add course type & sniippet

- snippets/language-coursescript.cson
> fix: snippets error

- snippets/language-coursescript.cson
> feat(snippets): update AIXA2PJet snippets

- package.json
- yarn.lock
> feat: update @laix/coursescript-lib version to 2.20.7

- snippets/language-coursescript.cson
> fix(aix): remove unused snippet

- snippets/language-coursescript.cson
> VocabBank snippet

- snippets/language-coursescript.cson
add activity snippet BellMCT && BellSpeakingMCQ
> add BellMCT && BellSpeakingMCQ

- snippets/language-coursescript.cson
> add  snippet

- package.json
- yarn.lock
sprout AIX 题型增加 Part_TR 以及题型展示优化
> feat: update @laix/coursescript-lib version

- package.json
- yarn.lock
update @laix/coursescript-lib to 2.20.10
> feat: update AIX Reveal

- snippets/language-coursescript.cson
> feat(aix): add snippet & change scorer to audio & delete layout

- package.json
- yarn.lock
> chore: update dep

- package.json
- snippets/language-coursescript.cson
- yarn.lock
> feat: update lib & fix snippet

- package.json
- yarn.lock
> feat: upgrade coursescript lib

- package.json
- snippets/language-coursescript.cson
> feat(aix): add 0.9 snippet

- package.json
- snippets/language-coursescript.cson
> fix(aix):  fix some snippet

- snippets/language-coursescript.cson
> session metadata add is_corona

- package.json
- snippets/language-coursescript.cson
- yarn.lock
> feat: add snippet

- package.json
- yarn.lock
> chore: update lib

- snippets/language-coursescript.cson
> snippet add bell mca

- components/App.jsx
- package.json
- snippets/language-coursescript.cson
- yarn.lock
> feat: add sprout lib

- components/App.jsx
- components/course-types.js
- package.json
- snippets/language-coursescript.cson
- yarn.lock
> sprout add animated & word course

- package.json
- snippets/language-coursescript.cson
- yarn.lock
> feat:aix1.7

- package.json
- yarn.lock
> hotfix:fix aix-1.7  coursescript-lib-sprout hooks

- components/App.jsx
- components/course-types.js
- package.json
- snippets/language-coursescript.cson
- yarn.lock
> feat: update coursescript-lib-sprout version to 2.27.0

- package.json
- snippets/language-coursescript.cson
- yarn.lock
> fix: snippets error & update coursescript-lib-sprout version to 2.27.1

- package.json
- snippets/language-coursescript.cson
- yarn.lock
> feat: support aix-1.9 snippets & update @laix/coursescript-lib-sprout version to 2.28.0

- package.json
- yarn.lock
> feat: update

- package.json
- snippets/language-coursescript.cson
- yarn.lock
> fix(snippets):  update snippets & coursescript-lib-sprout version

- components/course-types.js
- package.json
- snippets/language-coursescript.cson
- yarn.lock
> feat(sprout): support Sprout_GoodNight && aix-1.12 AT2PAdventureX

- package.json
- yarn.lock
> bell dubbing

- package.json
- snippets/language-coursescript.cson
- yarn.lock
> feat(sprout): support aix-2.1 snippets && update @laix/coursescript-lib-sprout to 2.32.0

- package.json
- snippets/language-coursescript.cson
- yarn.lock
> feat(sprout): support aix-2.2 snippets && update @laix/coursescript-lib-sprout to 2.33.0

- components/App.jsx
- components/course-types.js
- menus/language-coursescript.cson
- package.json
- yarn.lock
> ol short video

- package.json
- yarn.lock
> feat(sprout): update @laix/coursescript-lib-sprout to 2.34.0

- package.json
- snippets/language-coursescript.cson
- yarn.lock
> feat(sprout):  support aix-2.3 snippets && update @laix/coursescript-lib-sprout to 2.35.0

- package.json
- yarn.lock
> feat: update @laix/coursescript-lib-sprout version to 2.35.1

- package.json
- snippets/language-coursescript.cson
- yarn.lock
> feat(sprout): support aix-2.5 snippets & update  @laix/coursescript-lib-sprout to 2.36.0

- package.json
- snippets/language-coursescript.cson
- yarn.lock
> feat(sprout): support aix-2.6 snippets & update  @laix/coursescript-lib-sprout to 2.37.0

- components/App.jsx
- components/course-types.js
- package.json
- snippets/language-coursescript.cson
- yarn.lock
> feat: support lingokids compat reader course

- components/course-types.js
- package.json
- snippets/language-coursescript.cson
- yarn.lock
> fix(sprout): update PAT2AConversationFreeX snippets

- package.json
- snippets/language-coursescript.cson
- yarn.lock
> feat(sprout): support aix-2.9 snippets & update @laix/coursescript-lib-sprout to 2.39.0

- package.json
- snippets/language-coursescript.cson
- yarn.lock
> feat(sprout): support AIXPT2PTMatchingX preview && snippets

- package.json
- yarn.lock
> fix(sprout): cannot preview course

- package.json
- snippets/language-coursescript.cson
- yarn.lock
> feat(sprout): support AIXPAT2AAdventure(1|2) preview && snippets

- components/App.jsx
- components/course-types.js
- menus/language-coursescript.cson
- package.json
- snippets/language-coursescript.cson
- yarn.lock
> feat: add supra

- components/course-types.js
> feat: add ALIX_V2

- components/App.jsx
- components/course-types.js
- package.json
- yarn.lock
> feat(sprout): add SPROUT_GUIDANCE course

- components/App.jsx
- components/course-types.js
- package.json
- snippets/language-coursescript.cson
- yarn.lock
> feat: add ReadingComp

- components/course-types.js
> feat: add submarine_k12

- package.json
- snippets/language-coursescript.cson
- yarn.lock
> feat(sprout): support aix-2.12 snippets & update @laix/coursescript-lib-sprout to 2.43.0

- components/course-types.js
> feat: add industry

- package.json
> feat: 增加mct题型题干和选项高亮 

- package.json
- snippets/language-coursescript.cson
> feat: add listeningChoice

- package.json
- yarn.lock
> feat: update @laix/coursescript-lib-sprout version to 2.43.1

- package.json
- snippets/language-coursescript.cson
- yarn.lock
> feat(sprout): support aix-2.24 snippets & update @laix/coursescript-lib-sprout to 2.44.0

- package.json
> feat: cloze题型增加对回车符号支持

- components/App.jsx
- components/course-types.js
- package.json
- snippets/language-coursescript.cson
- yarn.lock
> feat: add hong-year course

- package.json
- snippets/language-coursescript.cson
> feat: supra add picname&picid

- package.json
- yarn.lock
> chore(deps): bump @laix/coursescript-lib-sprout from 2.45.0 to 2.45.1

- grammars/coursescript.cson
- package.json
- snippets/language-coursescript.cson
- yarn.lock
> feat(hongyear): support hongyear 0.2 course preview

- package.json
- yarn.lock
> chore(deps): bump @laix/coursescript-lib-sprout from 2.46.0 to 2.46.3

- package.json
- yarn.lock
> chore(deps): bump @laix/coursescript-lib-sprout from 2.46.3 to 2.46.4

- package.json
- yarn.lock
> feat: update wordguess

- components/App.jsx
- components/course-types.js
- package.json
- yarn.lock
> feat(campus): support campus course
